"""
NORA-CODE: Writes code — React, Python, SQL, Go.
Generates code stubs and file contents from architecture plans.
Phase 1: produces realistic mock output stored in job result.
"""
from typing import TypedDict


class CodeFile(TypedDict):
    path: str
    language: str
    lines: int
    stub: str


# Language detection by file extension
_EXT_LANG: dict[str, str] = {
    ".tsx": "TypeScript/React",
    ".ts": "TypeScript",
    ".jsx": "JavaScript/React",
    ".js": "JavaScript",
    ".py": "Python",
    ".sql": "SQL",
    ".go": "Go",
    ".json": "JSON",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".md": "Markdown",
}

_STUBS: dict[str, str] = {
    "TypeScript/React": "import React from 'react';\n\nexport default function Component() {\n  return <div>Hello NORA</div>;\n}\n",
    "Python": "from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get('/')\nasync def root():\n    return {'status': 'ok'}\n",
    "SQL": "-- Migration generated by NORA-CODE\nCREATE TABLE IF NOT EXISTS items (\n    id SERIAL PRIMARY KEY,\n    created_at TIMESTAMPTZ DEFAULT NOW()\n);\n",
    "TypeScript": "export interface Item {\n  id: number;\n  createdAt: string;\n}\n",
    "JSON": '{\n  "name": "nora-app",\n  "version": "1.0.0"\n}\n',
    "YAML": "version: '3.9'\nservices:\n  app:\n    build: .\n",
    "Markdown": "# NORA-Generated App\n\nGenerated by NORA-CODE.\n",
}


def _detect_language(path: str) -> str:
    for ext, lang in _EXT_LANG.items():
        if path.endswith(ext):
            return lang
    return "Text"


def generate_files(file_paths: list[str]) -> list[CodeFile]:
    """
    Generate code file stubs for each path in the list.
    Phase 1: produces deterministic stubs based on file extension.
    """
    results: list[CodeFile] = []
    for path in file_paths:
        lang = _detect_language(path)
        stub = _STUBS.get(lang, f"# Generated by NORA-CODE\n# File: {path}\n")
        results.append(CodeFile(
            path=path,
            language=lang,
            lines=len(stub.splitlines()),
            stub=stub,
        ))
    return results


def summarize_output(files: list[CodeFile]) -> dict:
    """Return a summary dict suitable for storing in job result."""
    by_language: dict[str, int] = {}
    for f in files:
        by_language[f["language"]] = by_language.get(f["language"], 0) + 1
    return {
        "total_files": len(files),
        "by_language": by_language,
        "file_paths": [f["path"] for f in files],
    }
