"""
NORA Phase 3 — Git Operations

Initialises a git repository in the project folder and creates the first commit.
"""
from __future__ import annotations

import subprocess

GIT_UNAVAILABLE = "git-unavailable"


def init_repo(project_path: str) -> str:
    """
    git init → configure identity → git add -A → git commit.
    Returns the short commit hash on success.
    Returns GIT_UNAVAILABLE if git is not installed.
    Returns a 'git-error: …' string on any other failure.
    """
    try:
        _run(["git", "init"], project_path)
        _run(["git", "config", "user.email", "nora@ai.builder"], project_path)
        _run(["git", "config", "user.name", "NORA AI"], project_path)
        _run(["git", "add", "-A"], project_path)
        _run(["git", "commit", "-m", "Initial commit — generated by NORA AI Phase 3"], project_path)
        result = _run(["git", "rev-parse", "--short", "HEAD"], project_path)
        return result.stdout.strip()
    except FileNotFoundError:
        return GIT_UNAVAILABLE
    except subprocess.CalledProcessError as exc:
        return f"git-error: {exc.stderr.strip()[:120]}"


def _run(cmd: list[str], cwd: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
        timeout=30,
    )
